"""Durable outbox for PDF report delivery.

Reports generated by proactive agents are copied here so they survive
``tempfile`` cleanup and can be resent on demand. Backed by
``data/outbox/`` (gitignored via the top-level ``data/`` entry in
``.gitignore``).

Report IDs
----------
- SP-YYYYMMDD-HHMM   — Sharp Picks
- HH-YYYYMMDD-HHMM   — Happy Hour Scout
- MP-YYYYMMDD-HHMM   — Familia Meal Planner

Each report is stored as up to three files:

    data/outbox/{report_id}.pdf         — the finalized PDF, when the job
                                          still builds one. Since 2026-09-03
                                          this is an ARCHIVE, not the delivery:
                                          reports go out as text and the PDF is
                                          sent only on request (see
                                          :mod:`ivy_core.text_delivery`).
    data/outbox/{report_id}.json        — metadata (no secrets)
    data/outbox/{report_id}.detail.json — per-item payload backing the MORE and
                                          WHY <n> reply commands

Metadata keys: report_id, job_name, recipient, content_summary,
generated_at (ISO-8601 UTC), status, send_attempts, latest_status.
"""

from __future__ import annotations

import json
import logging
import shutil
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

logger = logging.getLogger("ivy.outbox")

PROJECT_ROOT = Path(__file__).resolve().parent.parent
OUTBOX_DIR = PROJECT_ROOT / "data" / "outbox"
OUTBOX_TTL_HOURS = 72

# A report whose delivery was never confirmed is kept far longer than a
# delivered one, but not forever: without a cap, one stuck "pending" entry
# lives on disk indefinitely. 30 days is well past any realistic resend.
PENDING_TTL_DAYS = 30

# Recognized job prefixes and their canonical job names
_PREFIX_TO_JOB: Dict[str, str] = {
    "SP": "sharp_picks",
    "HH": "happy_hour",
    "MP": "familia_meal_planner",
}
_JOB_TO_PREFIX: Dict[str, str] = {v: k for k, v in _PREFIX_TO_JOB.items()}


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _ensure_outbox() -> None:
    OUTBOX_DIR.mkdir(parents=True, exist_ok=True)


def _meta_path(report_id: str) -> Path:
    return OUTBOX_DIR / f"{report_id}.json"


def _pdf_path(report_id: str) -> Path:
    return OUTBOX_DIR / f"{report_id}.pdf"


def _detail_path(report_id: str) -> Path:
    return OUTBOX_DIR / f"{report_id}.detail.json"


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def make_report_id(job_name: str) -> str:
    """Return a unique report ID for the given job.

    Format: ``PREFIX-YYYYMMDD-HHMM`` where PREFIX is SP / HH / MP.
    A monotonic suffix is appended if a collision occurs (rare in practice).
    """
    prefix = _JOB_TO_PREFIX.get(job_name, "XX")
    ts = datetime.now().strftime("%Y%m%d-%H%M")
    candidate = f"{prefix}-{ts}"
    _ensure_outbox()
    if not _meta_path(candidate).exists():
        return candidate
    # Collision: append seconds to guarantee uniqueness
    return f"{prefix}-{datetime.now().strftime('%Y%m%d-%H%M%S')}"


def save_report(
    report_id: str,
    pdf_path: Optional[str],
    job_name: str,
    recipient: str,
    content_summary: str,
    *,
    status: str = "pending",
) -> Optional[Path]:
    """Record a report in the outbox, copying its PDF when there is one.

    ``pdf_path`` may be None: text-only jobs still get an outbox entry so the
    reply commands (MORE / WHY / PDF) can find the report by ID. Returns the
    destination PDF path, or None when the report has no PDF.
    """
    _ensure_outbox()

    dest: Optional[Path] = None
    if pdf_path:
        dest = _pdf_path(report_id)
        shutil.copy2(pdf_path, dest)
        logger.info("Outbox: saved %s (%d bytes)", report_id, dest.stat().st_size)
    else:
        logger.info("Outbox: saved %s (text-only, no PDF)", report_id)

    meta: Dict[str, Any] = {
        "report_id": report_id,
        "job_name": job_name,
        "recipient": recipient,
        "content_summary": content_summary,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "status": status,
        "send_attempts": 0,
        "latest_status": status,
        "has_pdf": dest is not None,
    }
    _meta_path(report_id).write_text(json.dumps(meta, indent=2))

    # Self-prune on every write. cleanup_old_reports() has implemented a 72h
    # TTL since the outbox was added, but nothing ever called it — the outbox
    # had grown to 70 reports, 63 of them past the TTL. Doing it here means
    # retention holds even if no scheduled housekeeping job is installed.
    try:
        cleanup_old_reports()
    except Exception as exc:  # never let housekeeping break a delivery
        logger.warning("Outbox: cleanup after save failed: %s", exc)

    return dest


def load_report_meta(report_id: str) -> Optional[Dict[str, Any]]:
    """Load metadata for a report. Returns None if not found."""
    p = _meta_path(report_id)
    if not p.exists():
        return None
    try:
        return json.loads(p.read_text())
    except Exception as exc:
        logger.warning("Outbox: could not parse %s: %s", p, exc)
        return None


def update_report_status(
    report_id: str,
    status: str,
    *,
    attempts: Optional[int] = None,
) -> None:
    """Atomically update a report's status and optional attempt count."""
    meta = load_report_meta(report_id)
    if meta is None:
        logger.warning("Outbox: update_report_status — unknown report %s", report_id)
        return
    meta["status"] = status
    meta["latest_status"] = status
    if attempts is not None:
        meta["send_attempts"] = attempts
    _meta_path(report_id).write_text(json.dumps(meta, indent=2))


def get_outbox_pdf_path(report_id: str) -> Optional[Path]:
    """Return the outbox PDF path only if the file exists and is non-empty."""
    p = _pdf_path(report_id)
    return p if p.exists() and p.stat().st_size > 0 else None


def find_newest_pending(job_name: str) -> Optional[str]:
    """Return the newest pending/failed report ID for a given job, or None."""
    _ensure_outbox()
    candidates: List[tuple] = []
    for meta_file in OUTBOX_DIR.glob("*.json"):
        if meta_file.name.endswith(".detail.json"):
            continue
        try:
            meta = json.loads(meta_file.read_text())
            if (
                meta.get("job_name") == job_name
                and meta.get("status") in ("pending", "failed")
            ):
                candidates.append((meta["generated_at"], meta["report_id"]))
        except Exception:
            pass
    if not candidates:
        return None
    candidates.sort(key=lambda x: x[0], reverse=True)
    return candidates[0][1]


def save_detail(report_id: str, job_name: str, detail: Dict[str, Any]) -> Path:
    """Persist the per-item payload backing the MORE / WHY reply commands."""
    _ensure_outbox()
    payload = dict(detail)
    payload["report_id"] = report_id
    payload["job_name"] = job_name
    payload["saved_at"] = datetime.now(timezone.utc).isoformat()
    path = _detail_path(report_id)
    path.write_text(json.dumps(payload, indent=2))
    return path


def load_detail(report_id: str) -> Optional[Dict[str, Any]]:
    """Load a report's per-item payload. None if absent or unparseable."""
    path = _detail_path(report_id)
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text())
    except Exception as exc:
        logger.warning("Outbox: could not parse detail for %s: %s", report_id, exc)
        return None


def find_newest(job_name: str, *, with_detail: bool = False) -> Optional[str]:
    """Newest report ID for a job regardless of status.

    ``find_newest_pending`` only sees pending/failed reports, which is the
    wrong lens for reply commands: a report that was delivered as text is
    exactly the one MORE / WHY / PDF should act on.
    """
    _ensure_outbox()
    candidates: List[tuple] = []
    for meta_file in OUTBOX_DIR.glob("*.json"):
        if meta_file.name.endswith(".detail.json"):
            continue
        try:
            meta = json.loads(meta_file.read_text())
            if meta.get("job_name") != job_name:
                continue
            if with_detail and not _detail_path(meta["report_id"]).exists():
                continue
            candidates.append((meta["generated_at"], meta["report_id"]))
        except Exception:
            pass
    if not candidates:
        return None
    candidates.sort(key=lambda x: x[0], reverse=True)
    return candidates[0][1]


def list_reports(job_name: Optional[str] = None) -> List[Dict[str, Any]]:
    """All report metadata, newest first — optionally for one job.

    Reply commands need to look across every report Ivy sent (a bare "MORE"
    means the last one, whatever job it came from) and to pick one by the
    clock ("the 3pm picks"), neither of which find_newest* can express.
    """
    _ensure_outbox()
    metas: List[Dict[str, Any]] = []
    for meta_file in OUTBOX_DIR.glob("*.json"):
        if meta_file.name.endswith(".detail.json"):
            continue
        try:
            meta = json.loads(meta_file.read_text())
        except Exception:
            continue
        if not meta.get("report_id"):
            continue
        if job_name and meta.get("job_name") != job_name:
            continue
        metas.append(meta)
    metas.sort(key=lambda m: m.get("generated_at", ""), reverse=True)
    return metas


def job_name_for_report_id(report_id: str) -> Optional[str]:
    """Derive the job name from a report ID's prefix (fast, no I/O)."""
    prefix = report_id.split("-", 1)[0].upper()
    return _PREFIX_TO_JOB.get(prefix)


def cleanup_old_reports() -> int:
    """Remove aged-out outbox entries.

    Retention has three rules:

    1. The newest report of each job is ALWAYS kept, whatever its age. The
       MORE / WHY <n> / PDF reply commands resolve against it, and the weekly
       jobs (Happy Hour on Mondays, the meal planner on Sundays) are older
       than the 72h TTL for most of the week — enforcing the TTL alone left
       "MORE HAPPY HOUR" answering "I don't have a recent report" for four
       days out of every seven.
    2. A pending report survives the TTL (it may still be resent) up to
       PENDING_TTL_DAYS.
    3. Everything else goes once it is past OUTBOX_TTL_HOURS.

    Returns the number of report pairs deleted.
    """
    _ensure_outbox()

    # Rule 1: the newest report id per job, exempt from every age check.
    newest_per_job: Dict[str, tuple] = {}
    for meta_file in OUTBOX_DIR.glob("*.json"):
        if meta_file.name.endswith(".detail.json"):
            continue
        try:
            meta = json.loads(meta_file.read_text())
            job, when, rid = meta.get("job_name"), meta.get("generated_at", ""), meta["report_id"]
        except Exception:
            continue
        if job and when > newest_per_job.get(job, ("", ""))[0]:
            newest_per_job[job] = (when, rid)
    keep_ids = {rid for _, rid in newest_per_job.values()}
    now = datetime.now(timezone.utc)
    cutoff = now - timedelta(hours=OUTBOX_TTL_HOURS)
    pending_cutoff = now - timedelta(days=PENDING_TTL_DAYS)
    deleted = 0
    for meta_file in list(OUTBOX_DIR.glob("*.json")):
        if meta_file.name.endswith(".detail.json"):
            continue
        try:
            meta = json.loads(meta_file.read_text())
            raw_ts = meta.get("generated_at", "")
            if not raw_ts:
                continue
            ts = datetime.fromisoformat(raw_ts)
            if ts.tzinfo is None:
                ts = ts.replace(tzinfo=timezone.utc)
            # A pending report survives the normal TTL — it may still be
            # resent — but not the much longer PENDING_TTL_DAYS backstop.
            if meta["report_id"] in keep_ids:
                continue  # newest for its job — never aged out
            deadline = pending_cutoff if meta.get("status") == "pending" else cutoff
            if ts < deadline:
                report_id = meta["report_id"]
                meta_file.unlink(missing_ok=True)
                pdf = _pdf_path(report_id)
                if pdf.exists():
                    pdf.unlink()
                _detail_path(report_id).unlink(missing_ok=True)
                deleted += 1
                logger.debug("Outbox: cleaned up %s", report_id)
        except Exception as exc:
            logger.warning("Outbox: cleanup error on %s: %s", meta_file, exc)
    return deleted
