"""Durable outbox for PDF report delivery.

Reports generated by proactive agents are copied here so they survive
``tempfile`` cleanup and can be resent on demand. Backed by
``data/outbox/`` (gitignored via the top-level ``data/`` entry in
``.gitignore``).

Report IDs
----------
- SP-YYYYMMDD-HHMM   — Sharp Picks
- HH-YYYYMMDD-HHMM   — Happy Hour Scout
- MP-YYYYMMDD-HHMM   — Familia Meal Planner

Each report is stored as two files:

    data/outbox/{report_id}.pdf   — the finalized PDF
    data/outbox/{report_id}.json  — metadata (no secrets)

Metadata keys: report_id, job_name, recipient, content_summary,
generated_at (ISO-8601 UTC), status, send_attempts, latest_status.
"""

from __future__ import annotations

import json
import logging
import shutil
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

logger = logging.getLogger("ivy.outbox")

PROJECT_ROOT = Path(__file__).resolve().parent.parent
OUTBOX_DIR = PROJECT_ROOT / "data" / "outbox"
OUTBOX_TTL_HOURS = 72

# Recognized job prefixes and their canonical job names
_PREFIX_TO_JOB: Dict[str, str] = {
    "SP": "sharp_picks",
    "HH": "happy_hour",
    "MP": "familia_meal_planner",
}
_JOB_TO_PREFIX: Dict[str, str] = {v: k for k, v in _PREFIX_TO_JOB.items()}


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _ensure_outbox() -> None:
    OUTBOX_DIR.mkdir(parents=True, exist_ok=True)


def _meta_path(report_id: str) -> Path:
    return OUTBOX_DIR / f"{report_id}.json"


def _pdf_path(report_id: str) -> Path:
    return OUTBOX_DIR / f"{report_id}.pdf"


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def make_report_id(job_name: str) -> str:
    """Return a unique report ID for the given job.

    Format: ``PREFIX-YYYYMMDD-HHMM`` where PREFIX is SP / HH / MP.
    A monotonic suffix is appended if a collision occurs (rare in practice).
    """
    prefix = _JOB_TO_PREFIX.get(job_name, "XX")
    ts = datetime.now().strftime("%Y%m%d-%H%M")
    candidate = f"{prefix}-{ts}"
    _ensure_outbox()
    if not _meta_path(candidate).exists():
        return candidate
    # Collision: append seconds to guarantee uniqueness
    return f"{prefix}-{datetime.now().strftime('%Y%m%d-%H%M%S')}"


def save_report(
    report_id: str,
    pdf_path: str,
    job_name: str,
    recipient: str,
    content_summary: str,
    *,
    status: str = "pending",
) -> Path:
    """Copy the finalized PDF to the outbox and write metadata.

    Returns the destination PDF path. Excludes all secrets from metadata.
    """
    _ensure_outbox()

    dest = _pdf_path(report_id)
    shutil.copy2(pdf_path, dest)
    logger.info("Outbox: saved %s (%d bytes)", report_id, dest.stat().st_size)

    meta: Dict[str, Any] = {
        "report_id": report_id,
        "job_name": job_name,
        "recipient": recipient,
        "content_summary": content_summary,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "status": status,
        "send_attempts": 0,
        "latest_status": status,
    }
    _meta_path(report_id).write_text(json.dumps(meta, indent=2))
    return dest


def load_report_meta(report_id: str) -> Optional[Dict[str, Any]]:
    """Load metadata for a report. Returns None if not found."""
    p = _meta_path(report_id)
    if not p.exists():
        return None
    try:
        return json.loads(p.read_text())
    except Exception as exc:
        logger.warning("Outbox: could not parse %s: %s", p, exc)
        return None


def update_report_status(
    report_id: str,
    status: str,
    *,
    attempts: Optional[int] = None,
) -> None:
    """Atomically update a report's status and optional attempt count."""
    meta = load_report_meta(report_id)
    if meta is None:
        logger.warning("Outbox: update_report_status — unknown report %s", report_id)
        return
    meta["status"] = status
    meta["latest_status"] = status
    if attempts is not None:
        meta["send_attempts"] = attempts
    _meta_path(report_id).write_text(json.dumps(meta, indent=2))


def get_outbox_pdf_path(report_id: str) -> Optional[Path]:
    """Return the outbox PDF path only if the file exists and is non-empty."""
    p = _pdf_path(report_id)
    return p if p.exists() and p.stat().st_size > 0 else None


def find_newest_pending(job_name: str) -> Optional[str]:
    """Return the newest pending/failed report ID for a given job, or None."""
    _ensure_outbox()
    candidates: List[tuple] = []
    for meta_file in OUTBOX_DIR.glob("*.json"):
        try:
            meta = json.loads(meta_file.read_text())
            if (
                meta.get("job_name") == job_name
                and meta.get("status") in ("pending", "failed")
            ):
                candidates.append((meta["generated_at"], meta["report_id"]))
        except Exception:
            pass
    if not candidates:
        return None
    candidates.sort(key=lambda x: x[0], reverse=True)
    return candidates[0][1]


def job_name_for_report_id(report_id: str) -> Optional[str]:
    """Derive the job name from a report ID's prefix (fast, no I/O)."""
    prefix = report_id.split("-", 1)[0].upper()
    return _PREFIX_TO_JOB.get(prefix)


def cleanup_old_reports() -> int:
    """Remove outbox entries older than OUTBOX_TTL_HOURS unless still pending.

    Returns the number of report pairs deleted.
    """
    _ensure_outbox()
    cutoff = datetime.now(timezone.utc) - timedelta(hours=OUTBOX_TTL_HOURS)
    deleted = 0
    for meta_file in list(OUTBOX_DIR.glob("*.json")):
        try:
            meta = json.loads(meta_file.read_text())
            if meta.get("status") == "pending":
                continue  # Never remove a pending report
            raw_ts = meta.get("generated_at", "")
            if not raw_ts:
                continue
            ts = datetime.fromisoformat(raw_ts)
            if ts.tzinfo is None:
                ts = ts.replace(tzinfo=timezone.utc)
            if ts < cutoff:
                report_id = meta["report_id"]
                meta_file.unlink(missing_ok=True)
                pdf = _pdf_path(report_id)
                if pdf.exists():
                    pdf.unlink()
                deleted += 1
                logger.debug("Outbox: cleaned up %s", report_id)
        except Exception as exc:
            logger.warning("Outbox: cleanup error on %s: %s", meta_file, exc)
    return deleted
